modLoader = "javafml"
loaderVersion = "[35,37)"
license = "ComputerCraft Public License"
issueTrackerURL = "https://github.com/BastouP411/bperipherals/issues"

[[mods]]
modId = "bperipherals"
version = "1.2.0"
displayName = "BPeripherals"
#updateJSONURL="http://myurl.me/"
displayURL = "https://github.com/BastouP411/bperipherals/wiki"
logoFile = "logo.png"
#credits=""
authors = "BastouP"
    description='''
    This is a mod that adds peripherals to ComputerCraft.
    '''

[[dependencies.bperipherals]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.16,37)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bperipherals]]
    modId="computercraft"
    mandatory=true
    versionRange="[1.95,)"
    ordering="NONE"
    side="BOTH"
